import json
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib import style
import time
from math import pi, cos, sin
import numpy as np

#-----------------------------------------------------------------------------------
# Plots from a text file of weather date
# Uses text file generated by WeatherStationTCP_SRT9.py
# Written by: Sarah Kinney SRT9
# ----------------------------------------------------------------------------------

data_dict = dict(time=["2021-10-03 21:53:19"], temperature_C=[0], wind_max_m_s=[0], wind_avg_m_s=[0], wind_dir_deg=[0])
weather_fname = 'dev_weather_hearne.txt'

def parse_packets():
    all_data = open(weather_fname, 'r').readlines()
    for packet in all_data:
        try:
            packet_dict = json.loads(packet)
            #print(packet_dict["model"])
            for key in data_dict.keys():
                if packet_dict["model"] == "Fineoffset-WH24" and packet_dict["id"] == 247:
                    if key == "temperature_C":
                        data_dict[key].append(packet_dict[key]*9/5+32)  # convert to F
                    elif key == "wind_max_m_s":
                        data_dict[key].append(packet_dict[key]*3.281)   # convert to ft/s
                    elif key == "wind_avg_m_s":
                        data_dict[key].append(packet_dict[key]*3.281)   # convert to ft/s
                    elif key == "wind_dir_deg":
                        data_dict[key].append(packet_dict[key] + 90 + 180)    # shift by 90 degrees so N is at top and adjust for direction
                    else:
                        data_dict[key].append(packet_dict[key])
        except(json.decoder.JSONDecodeError):
            print("JSON error, skipping packet", packet)


def animate(i):
    parse_packets()
    
    if len(data_dict["time"]) < 30:
        print("less than")
        full_timestamp_list = data_dict["time"][0:-1]
        radians = [element * pi / 180 for element in data_dict["wind_dir_deg"][0:-1]]
    else:
        full_timestamp_list = data_dict["time"][-31:-1]
        radians = [element * pi / 180 for element in data_dict["wind_dir_deg"][-31:-1]]
    

    strip_timestamp_list = range(0, len(full_timestamp_list))
    alphas = np.linspace(0, 1, len(radians))
    print(alphas)

    ax1.clear()
    ax2.clear()
    ax3.clear()
    ax4.clear()
    
    ax1.set(ylabel='temperature (F)')
    ax2.set(ylabel='wind gusts (ft/s)')
    ax3.set(ylabel='wind average (ft/s)')
    ax4.set(xlabel='wind direction')

    if len(data_dict["time"]) < 30:
        wind_avg = data_dict["wind_avg_m_s"][0:-1]
        ax1.plot(strip_timestamp_list, data_dict["temperature_C"][0:-1], linewidth=1)
        ax2.plot(strip_timestamp_list, data_dict["wind_max_m_s"][0:-1], linewidth=1)
        ax3.plot(strip_timestamp_list, wind_avg, linewidth=1)
        ax4.plot(radians, strip_timestamp_list, linewidth=1)
    else:
        wind_avg = data_dict["wind_avg_m_s"][-31:-1]
        ax1.plot(strip_timestamp_list, data_dict["temperature_C"][-31:-1], linewidth=1)
        ax2.plot(strip_timestamp_list, data_dict["wind_max_m_s"][-31:-1], linewidth=1)
        ax3.plot(strip_timestamp_list, wind_avg, linewidth=1)
        
        for i in range(20, len(radians)):
            radius = strip_timestamp_list[i]
            transparency = (-20+radius)/10
            ax4.quiver(0,0, wind_avg[i]*cos(radians[i]), wind_avg[i]*sin(radians[i]), scale=60, alpha=transparency)
            #ax4.set_theta_zero_location("W")
            ax4.set_thetagrids((90, 180, 270, 0), ("N", "W", "S", "E"))
            ax4.plot(radians, wind_avg, linewidth=0)
            

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------             
style.use('fivethirtyeight')

fig = plt.figure()
ax1 = plt.subplot(221)

ax2 = plt.subplot(222)
ax3 = plt.subplot(223)
ax4 = plt.subplot(224, projection='polar')

ani = animation.FuncAnimation(fig, animate, interval=1000)
plt.tight_layout()
plt.show()





animate()

    
