#!/usr/bin/env bash

##NECESSARY JOB SPECIFICATIONS
#BSUB -J srt_fs_sim         #Set the job name to "ExampleJob2"
#BSUB -L /bin/bash           #Uses the bash login shell to initialize the job's execution environment.
#BSUB -W 0:2                #Set the wall clock limit to 6hr and 30min
#BSUB -n 5                  #Request 10 cores
#BSUB -R "span[ptile=5]"    #Request 10 cores per node.
#BSUB -R "rusage[mem=1000]"  #Request 2560MB per process (CPU) for the job
#BSUB -M 1000                #Set the per process enforceable memory limit to 2560MB.
#BSUB -o fs_stdout.%J      #Send stdout and stderr to "Example2Out.[jobID]"

#cd $SCRATCH      # Change current directory to /scratch/user/[netID]/
ml purge         # Purge all modules
ml Matlab/R2018a   # Load the intel/2016b module
ml               # List all currently loaded modules

cd ~/fs
matlab -nodisplay -nosplash -nodesktop -r "srt_fs_main(\"./input/theseus_hybrid_irec.inp\")"   # Run "myProgram.o"